# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/npis', type: :request do
  # Npi. As you add validations to Npi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Npi.create! valid_attributes
      get npis_url
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Npi' do
        expect do
          post npis_url, params: { npi: valid_attributes }
        end.to change(Npi, :count).by(1)
      end

      it 'redirects to the created npi' do
        post npis_url, params: { npi: valid_attributes }
        expect(response).to redirect_to(npi_url(Npi.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Npi' do
        expect do
          post npis_url, params: { npi: invalid_attributes }
        end.to change(Npi, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post npis_url, params: { npi: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end
end
